# Generated by Django 4.0.4 on 2022-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_department_student_email_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('limit', models.IntegerField(default=30)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('students', models.ManyToManyField(blank=True, null=True, to='students.student')),
            ],
        ),
    ]
